config/routes.rb
Rails.application.routes.draw do
  resources :projects

  root to: "pages#landing"
  get "/about" => "pages#about"
  get "/contact" => "pages#contact"

  get "/dashboard" => "admin#dashboard"
  get "/login" => "admin#new"
  post "/login" => "admin#create"
  delete "/logout" => "admin#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# title                   string
# description             text
# specifications          text
# details                 text
class Project < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :specifications, presence: true
  validates :details, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :redirect_if_logged_in!, only: %i[new create]
  before_action :require_login!, only: :dashboard

  # GET /dashboard
  def dashboard; end

  # GET /login
  def new; end

  # POST /login
  def create
    if admin_authenticate
      login
      redirect_to dashboard_path
    else
      render :new
    end
  end

  # DELETE /logout
  def destroy
    logout
    redirect_to login_path
  end

  private

  def redirect_if_logged_in!
    redirect_to dashboard_path if logged_in?
  end

  def admin_authenticate
    params["username"] == ENV["portfolio_admin_username"] &&
    params["password"] == ENV["portfolio_admin_password"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  def require_login!
    redirect_to login_path unless logged_in?
  end

  def login
    session[:admin] = true
  end

  def logout
    session.delete :admin
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing; end

  def about; end

  def contact; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_admin, only: %i[new edit]
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:title, :description, :specifications, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:admin]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/new.html.erb
<%= form_tag("/login", method: "post") do %>
  <%= text_field_tag :username, nil, placeholder: "Username" %>
  <%= password_field_tag :password, nil, placeholder: "Password" %>
  <%= submit_tag %>
<% end %>

app/views/layouts/_navbar.html.erb
<li><a><%= link_to 'Home', root_path %></a></li>
<li><a><%= link_to 'Projects', projects_path %></a></li>
<li><a><%= link_to 'Blog', '#' %></a></li>
<li><a><%= link_to 'About', about_path %></a></li>
<li><a><%= link_to 'Contact', contact_path %></a></li>
<% if logged_in? %>
  <li><a><%= link_to 'Dashboard', dashboard_path %></a></li>
  <li><a><%= link_to 'Logout', logout_path, method: :delete %></a></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/landing.html.erb
<h1>Landing</h1>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :specifications %>
    <%= form.text_area :specifications %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Specifications</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.specifications %></td>
        <td><%= project.details %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Specifications:</strong>
  <%= @project.specifications %>
</p>

<p>
  <strong>Details:</strong>
  <%= @project.details %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>